import "./globals.css";
import { Inter } from "next/font/google";
import ReduxProvider from "./redux/ReduxProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Quizes",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-slate-100" style={{ width: "100%" }}>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
